apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vmxtllshn-nodejs-gitops
  description: This is GitOps manifest for vmxtllshn-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vmxtllshn-nodejs
    backstage.io/kubernetes-id: vmxtllshn-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vmxtllshn-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vmxtllshn-nodejs
